# @name Register
POST http://localhost:5000/api/v1/register
Content-Type: application/json

{
  "fullName": "Prinz Eugen",
  "email"   : "test12@root.com",
  "password" : "thisisroot",
  "gender": "Female",
  "phone": "08123456789",
  "address": "Kiel, Germany, Kiel"
}

###

# @name Login
POST http://localhost:5000/api/v1/login
Content-Type: application/json
//Authorization: 

{
  "email"   : "admin@root.com",
  "password" : "thisisroot"
}

###

# @name getAllUser
GET http://localhost:5000/api/v1/user
Content-Type: application/json

###

# @name getUser
GET http://localhost:5000/api/v1/user/5
Content-Type: application/json

###

# @name deleteUser
DELETE http://localhost:5000/api/v1/user/2
Content-Content-Type: application/json

###

# @name getAllCategory
GET http://localhost:5000/api/v1/category
Content-Type: application/json

###

# @name getCategory
GET http://localhost:5000/api/v1/category/9
Content-Type: applicaton/json

###

# @name addCategory
POST http://localhost:5000/api/v1/category
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjAyNDg4NTUyfQ.YWsOeikkf3-fvwTKRw5OhNLLi4SbzVxZlbd7Zl7WnMA

{
  "name": "Comedy"
}

###

# @name editCategory
PATCH http://localhost:5000/api/v1/category/7
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjAyNDg4NTUyfQ.YWsOeikkf3-fvwTKRw5OhNLLi4SbzVxZlbd7Zl7WnMA

{
  "name": "Computer"
}

###

# @name deleteCategory
DELETE  http://localhost:5000/api/v1/category/9
Content-Type: application/json 
//Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjAyNDg4NTUyfQ.YWsOeikkf3-fvwTKRw5OhNLLi4SbzVxZlbd7Zl7WnMA

###

# @name getAllBook
GET http://localhost:5000/api/v1/book
Content-Type: application/json

###

# @name getBook
GET http://localhost:5000/api/v1/book/1
Content-Type: application/json

###

# @name addBook
POST http://localhost:5000/api/v1/book
Content-Type: application/json 
//Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjAyNDg4NTUyfQ.YWsOeikkf3-fvwTKRw5OhNLLi4SbzVxZlbd7Zl7WnMA

{
	"title": "How to Train Your Dragon",
	"author": "Willy Wonka",
	"publication": "April 2001",
	"categoryId": 4,
	"userId": 4,
	"page": "195",
	"isbn": 451234,
	"about": "Lorem Ipsum, this is just a dummy. There's nothing to see here, really.",
	"file": "howToTrainYourDragon.epub",
	"thumbnail": "howToTrainYourDragon.jpg",
	"status": "null"
}

###

# @name editBook
PATCH  http://localhost:5000/api/v1/book/13
Content-Type: application/json 
//Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjAyNDg4NTUyfQ.YWsOeikkf3-fvwTKRw5OhNLLi4SbzVxZlbd7Zl7WnMA

{
	"title": "How to Install RAM",
	"author": "Pink Guy",
	"publication": "May 2020",
	"categoryId": 5,
	"userId": 4,
	"page": "250",
	"isbn": 123456789,
	"about": "Lorem Ipsum, this is just a dummy. There's nothing to see here, really.",
	"file": "theDominator.epub",
	"thumbnail": "howToInstalRAM.jpg",
	"status": "null"
}

###

# @name deleteBook
DELETE  http://localhost:5000/api/v1/book/13
Content-Type: application/json 
//Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjAyNDg4NTUyfQ.YWsOeikkf3-fvwTKRw5OhNLLi4SbzVxZlbd7Zl7WnMA

###